---
driver:
  name: vagrant
  synced_folders:
   - ["~", "/dir", "create: false"]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
  - name: windows-2012r2
    driver_config:
      box:  mwrock/windows2012r2


suites:
  - name: default
    run_list:
      - recipe[atom]
      - recipe[apm_packages]

verifier:
  name: inspec
